runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT main:app

# GCP scaling instances range
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4

runtime_config:
  python_version: 3

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: gohst-names:europe-west2:phantom-ghost-names

# GCP file to serve
handlers:
- url: .*
  script: main.app

env_variables:
  USE_GCP_DB: True
  GCP_REDIRECT_URI: 'https://gohst-names.uc.r.appspot.com'

