# Generated by Django 3.2 on 2021-04-24 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GhostName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, unique=True, verbose_name='Ghost Name')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Gosht Description')),
                ('first_name', models.TextField(blank=True, max_length=40, null=True, verbose_name='First Name')),
                ('last_name', models.TextField(blank=True, max_length=40, null=True, verbose_name='Last Name')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
